#======================================================================#
#                                                                      #
#  ██████╗ ██╗      █████╗ ██╗   ██╗███████╗██████╗                    #
#  ██╔══██╗██║     ██╔══██╗╚██╗ ██╔╝██╔════╝██╔══██╗                   #
#  ██████╔╝██║     ███████║ ╚████╔╝ █████╗  ██████╔╝                   #
#  ██╔═══╝ ██║     ██╔══██║  ╚██╔╝  ██╔══╝  ██╔══██╗                   #
#  ██║     ███████╗██║  ██║   ██║   ███████╗██║  ██║                   #
#  ╚═╝     ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝                   #
#                                                                      #
#    ███████╗███████╗████████╗████████╗██╗███╗   ██╗ ██████╗ ███████╗  #
#    ██╔════╝██╔════╝╚══██╔══╝╚══██╔══╝██║████╗  ██║██╔════╝ ██╔════╝  #
#    ███████╗█████╗     ██║      ██║   ██║██╔██╗ ██║██║  ███╗███████╗  #
#    ╚════██║██╔══╝     ██║      ██║   ██║██║╚██╗██║██║   ██║╚════██║  #
#    ███████║███████╗   ██║      ██║   ██║██║ ╚████║╚██████╔╝███████║  #
#    ╚══════╝╚══════╝   ╚═╝      ╚═╝   ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚══════╝  #
#                                                                      #
#======================================================================#
#
# WARNING:
# The configuration files may change with new versions of the plugin. You will need to copy the
# changes over to your local files, or generate new configuration files.
#
# You can find the latest version of all the configuration files here:
# https://github.com/limbo56/PlayerSettings/wiki/Configurations
#

# General Configuration Section
general:
  debug: false
  # This property toggles the plugin usage metrics
  # * Disabling this option does not affect plugin functionality
  # * Collected data is anonymous, providing server-related information.
  metrics: true
  # This property controls the update message sent to server operators upon joining
  update-alert: true
  # Controls whether a warning message is displayed when a security/authentication plugin is causing issues
  # * Setting this to false will disable the warning message
  offline-warning: true
  # List of worlds where the plugin will be enabled
  #
  # * Use '*' to enable the plugin in all worlds
  worlds:
    - "world"
  # List of metadata tags to treat as NPCs. This is used to ignore targets of the stacker setting
  #
  # * By default, the "Citizens" plugin adds the "NPC" metadata tag to all of its entities
  npc-metadata:
    - "NPC"
  # A map of aliases to use when displaying the value of a setting
  #
  # * Values can be mapped to an alias or a list of aliases
  # * The first alias in the list will be used to display the setting value
  # * The alias for value 0 will be used to display setting values less than 1
  value-aliases:
    0: [ "off", "x0" ]
    1: [ "on", "x1" ]
    2: "x2"
    3: "x3"
    4: "x4"
    5: "x5"
    6: "x6"
    7: "x7"
    8: "x8"
    9: "x9"
    10: "x10"

# Menu Configuration Section
menu:
  name: "&6&lSettings"
  size: 54
  # Enable or disable the toggle button below settings
  toggle-button: true
  # This section defines sounds played when a player interacts with a setting
  #
  # Format: [Sound], [Volume], [Pitch]
  # Examples:
  # - ENTITY_PLAYER_BURP, 2.5f, 0.5
  # - ENTITY_PLAYER_BURP, 0.5, 1f
  # - MUSIC_END, 10f
  sounds:
    setting-toggle-on: "BLOCK_NOTE_BLOCK_HARP, 1, 1"
    setting-toggle-off: "BLOCK_NOTE_BLOCK_HARP, 1, -99"

# Commands configuration section
commands:
  # The default command that '/settings' will perform.
  #
  # * By default, the command will execute the '/settings open' command
  #
  # Available Options:
  # * open - Opens the settings menu
  # * help - Send the settings help message
  default: "open"
  open:
    enabled: true
  help:
    enabled: true
  reload:
    enabled: true
  set:
    enabled: true
  get:
    enabled: true

# Data Storage Configuration Section
storage:
  # The storage type to use when storing player settings
  #
  # Available options:
  # - sqlite (default)
  # - sql
  # - mongodb
  type: "sqlite"
  # The host address of the settings storage database
  #
  # Formats:
  # * (sqlite, sql)
  #   | [Host]:[Port]
  # * (mongodb)
  #   | mongodb://[User]:[Pass]@[Host]:[Port]/[Options]
  #   Recommended Options: maxPoolSize=20&w=majority&compressors=snappy
  #   References:
  #   - URI: https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/connection/connect/#connection-uri
  #   - Options: https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/connection/connection-options/
  host: "localhost:3306"
  # The name of the database/collection to store settings data in
  #
  # * The database/collection must already exist before running the plugin!
  database: "playersettings"
  # The credentials used to authenticate with the database and establish connections
  #
  # * IGNORED BY STORAGE TYPE "mongodb". Instead, specify your database credentials inside the "host" connection uri.
  username: "root"
  password: "root"
  # Connection Pool Configuration
  #
  # * IGNORED BY STORAGE TYPE "mongodb". Instead, specify your pool properties inside the "host" connection uri.
  pool:
    # Maximum number of connections to the database
    # https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
    maximum-pool-size: 10
    # Minimum number of idle connections to maintain in the pool
    #
    # * For maximum performance and responsiveness to spike demands, we recommend not setting this
    #   value and instead allowing the pool to act as a fixed size connection pool
    #   (set this value to the same as 'maximum-pool-size')
    minimum-idle: 10
    # Maximum lifetime in milliseconds of a connection in the pool
    #
    # * We strongly recommend setting this value to at least 30 seconds shorter than any database
    #   or infrastructure imposed connection time limit
    max-lifetime: 1800000 # 30 minutes
    # Frequency of keep alive attempts to prevent connection timeouts
    #
    # * This value must be less than the 'max-lifetime' value
    # * Setting the value to zero will disable the keep alive functionality
    keep-alive-time: 0
    # Maximum time to wait for a connection from the pool before timing out in milliseconds
    connection-timeout: 5000 # 5 seconds
  # Connection Properties
  #
  # * IGNORED BY STORAGE TYPE "mongodb". Instead, specify your database properties inside the "host" connection uri.
  properties:
    use-unicode: true
    character-encoding: utf8
    use-ssl: false
    verify-server-certificate: false
