# Settings Configuration Format:
#
# | A unique name to identify this setting
# example-setting:
#   | Property to toggle the setting
#   enabled: true
#
#   | The display name of the setting
#   name: "&aExample"
#
#   | The default value players have for this setting
#   default: 0
#
#   | Maximum value allowed (optional, default is 1)
#   max: 1
#
#   | List of events/actions that should trigger the side effects for the current value of the setting
#   |
#   | Available triggers:
#   | - join: Trigger when the player joins
#   | - respawn: Triggers when a player respawns
#   triggers: ["join", "respawn"]
#
#   | Toggleable settings:
#   | A list of commands that will be executed when the setting is enabled and disabled
#   |
#   | * If the 'values' property is defined these callbacks will be ignored
#   onEnable:
#     - "me %player% %value%"
#   onDisable:
#     - "me %player% %value%"
#
#   | Multi level settings:
#   | A map of values that each hold a list of commands that will be executed respective to the
#   | value of the setting
#   |
#   | * You can run a command in the console by appending 'SUDO ' to the command
#   | * The 'default' section allows your setting to fallback to a default list of commands when the
#   |   value the setting was changed to is not defined in this list
#   values:
#     0:
#       - "me %player% %value%"
#     1:
#       - "me %player% %value%"
#     default:
#       - "me %player% %value%"
#
#   | Section to define overrides for this specific setting
#   overrides:
#     | Override properties of the enabled/disabled items
#     |
#     | * Use the same properties that you pass when configuring an item in the 'items.yml' file
#     | * No need to re-define every property for the item, just the ones you want to override
#     enabled-item:
#       name: "&aEnabled"
#       material: LIME_STAINED_GLASS
#     disabled-item:
#       name: "&cDisabled"
#       material: RED_STAINED_GLASS
#
#     | Override the sounds played when a player interacts with a setting
#     |
#     | * Format: [Sound], [Volume], [Pitch]
#     sounds:
#       setting-toggle-on: "BLOCK_NOTE_BLOCK_HARP, 1, 1"
#       setting-toggle-off: "BLOCK_NOTE_BLOCK_HARP, 1, -99"
#
#     | A map of aliases to use when displaying the value of a setting
#     |
#     | * Values can be mapped to an alias or a list of aliases
#     | * The first alias in the list will be used to display the setting value
#     | * The alias for value 0 will be used to display all setting values less than 1
#     value-aliases:
#       0: ["off", "x0"]
#       1: ["on", "x1"]
#       2: "x2"
#       3: "x3"
#       4: "x4"
#       5: "x5"
#       6: "x6"
#       7: "x7"
#       8: "x8"
#       9: "x9"
#       10: "x10"
#
# Examples:
#
# | AuthMeReloaded https://www.spigotmc.org/resources/authmereloaded.6269/
# premium-setting:
#   enabled: true
#   name: "&dPremium"
#   default: 0
#   triggers: []
#   onEnable:
#     - "SUDO premium %player%"
#   onDisable:
#     - "SUDO cracked %player%"
#
# | GMusic https://www.spigotmc.org/resources/gmusic-%E2%9C%A8-modern-jukebox-music-note-block-plugin-1-13-x-1-19-x.84004/
# radio-setting:
#   enabled: true
#   name: "&dRadio"
#   default: 0
#   triggers: []
#   onEnable:
#     - "music resume"
#   onDisable:
#     - "music pause"

fly-setting:
  enabled: true
  name: "&6Fly"
  default: 0
  max: 10
  # Saves the flight state when a player leaves the game server
  save-state: true
  # Forces the player into flight mode when they join the game server
  #
  # * This property will respect if save-state is enabled i.e. it won't force flight mode if the player had flight disabled
  force-on-join: false
  triggers: [ "join", "respawn" ]
